#!/bin/sh
echo "installing bootlogo access ..."
mv /boot/bootlogo.mvi /boot/bootlogo.mvi.access

if [ -f /boot/bootvideo.mkv ]; then
	mv /boot/bootvideo.mkv /boot/bootvideo.mkv.bak
	echo ""
	echo "Sichere Bootvideo..."
	echo ""
else
	echo ""
	echo "Kein Bootvideo gefunden...skip"
	echo""
fi

exit 0
